openapi: 3.0.3
info:
  version: "1.1"
  x-api-name: Egg-Move-Calc-API
  x-api-type: domain
  contact:
    email: Sebastian.Bekkvik.Aas@gmail.com
  title: EMC - Egg Move Calculator API
  description: >-
    Endpoints for retrieving egg move calculations via frontend.
servers:
  - description: API Endpoint URL
    url: none

paths:
  /calc: # Rename
    get:
      tags:
        - Egg Move Chain
      summary: Get an egg move chain
      description: |
        Get a chain of pairings to give the specified species the specified move via egg moves.
      operationId: "getEggMoveChain"

      parameters:
        #query
        - $ref: "#/components/parameters/speciesId"
        - $ref: "#/components/parameters/moveId"

      responses:
        '200':
          description: Egg move chain calculated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eggChainResponse"

        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /calc/moves:
    get:
      tags:
        - Egg Moves
      summary: Get all egg moves for a species
      description: |
        Get all moves that the specified species can learn via breeding.
      operationId: "getEggMovesForSpecies"

      parameters:
        #query
        - $ref: "#/components/parameters/speciesId"

      responses:
        '200':
          description: Egg moves retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/eggMovesResponse"

        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  parameters:
    speciesId:
      name: speciesId
      description: The ID of the species.
      required: true
      schema:
        type: integer
      in: query
    moveId:
      name: moveId
      description: The ID of the move.
      required: true
      schema:
        type: integer
      in: query

  schemas:
    eggChainResponse:
      description: Successful Response
    eggMovesResponse:
      description: Successful Response
      type: array
      items:
        $ref: '#/components/parameters/moveId'

  responses:
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not Found
    ServerError:
      description: Internal Server Error